### ISSUE TITLE
Storage should have a Get method

### ISSUE THREAD

**Issue by ammario** [Clever/leakybucket#21]
It only makes sense to have some kind of `Get(name string) Bucket` method as each bucket is keyed by a name.

**Comment by mohit** [comment]
Please feel free to reopen the ticket with a use case if this is still an issue.

**Comment by dwalker-va** [comment]
The interface is what is confusing. It is called `Create` but it actually does a `GetOrCreate`. So while there's no real need for a `Get`, it does look that way if you look at the `Storage` interface and its docstring (which does not mention the Get behaviour at all).
